import * as stylex from '@stylexjs/stylex'

const mobile = '@media (max-width: 40rem)'

export const styles = stylex.create({
  main: {
    width: { default: 'min(76rem, calc(100% - 4.5rem))', [mobile]: 'min(100% - 1.75rem, 76rem)' },
    margin: '0 auto',
  },
  dashboard: {
    padding: { default: '3.5rem 0 6.75rem', [mobile]: '1.75rem 0 3.5rem' },
  },
  header: {
    display: 'flex',
    alignItems: { default: 'start', [mobile]: 'stretch' },
    justifyContent: 'space-between',
    flexDirection: { default: 'row', [mobile]: 'column' },
    gap: { default: '3.5rem', [mobile]: '0.875rem' },
    minHeight: { default: '20rem', [mobile]: '16rem' },
  },
  headerActions: {
    display: 'flex',
    alignItems: 'flex-start',
    flexFlow: { default: 'row nowrap', [mobile]: 'row wrap' },
    gap: '0.75rem',
  },
  notificationControl: {
    display: 'grid',
    justifyItems: { default: 'end', [mobile]: 'start' },
    gap: '0.35rem',
  },
  headerButton: { alignSelf: { default: 'auto', [mobile]: 'start' } },
  notificationButton: { margin: 0, alignSelf: { default: 'auto', [mobile]: 'start' } },
  notificationError: {
    maxWidth: '16rem',
    color: 'var(--error)',
    fontSize: '0.75rem',
    textAlign: 'right',
  },
  eyebrow: {
    margin: 0,
    color: 'var(--on-surface)',
    fontSize: '0.75rem',
    fontWeight: 500,
    letterSpacing: '0.08em',
    lineHeight: '1rem',
    textTransform: 'uppercase',
  },
  games: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(16rem, 1fr))',
    gap: '0.875rem',
  },
  game: {
    display: 'flex',
    minHeight: '10rem',
    flexDirection: 'column',
    justifyContent: 'space-between',
    gap: '1.5rem',
    padding: '1.5rem',
    backgroundColor: { default: '#001f1ebf', ':hover': 'var(--secondary)' },
    borderStyle: 'solid',
    borderWidth: '1px',
    borderColor: { default: 'var(--border)', ':hover': '#ffffff70' },
    borderRadius: '0.5rem',
    transition: 'background-color 150ms ease, border-color 150ms ease',
  },
  gameTitle: {
    display: 'flex',
    alignItems: { default: 'end', [mobile]: 'start' },
    justifyContent: 'space-between',
    flexDirection: { default: 'row', [mobile]: 'column' },
    gap: { default: '1rem', [mobile]: '0.5rem' },
  },
  gameTitleLink: {
    flex: 'none',
    color: '#ffffffbf',
    fontSize: '0.875rem',
    letterSpacing: '0.025rem',
    whiteSpace: 'nowrap',
  },
  tableWrap: {
    overflowX: 'auto',
    backgroundColor: '#001f1ebf',
    border: '1px solid var(--border)',
    borderRadius: '0.5rem',
  },
  scoreDetail: { display: { default: 'table-cell', [mobile]: 'none' } },
  login: {
    display: 'grid',
    minHeight: '100vh',
    padding: { default: '3.5rem 0', [mobile]: '1.75rem 0 3.5rem' },
    placeItems: 'center',
  },
  loading: {
    display: 'grid',
    minHeight: '100vh',
    padding: '3.5rem 0',
    placeItems: 'center',
  },
  loginForm: {
    width: 'min(36rem, 100%)',
    padding: { default: '3.5rem', [mobile]: '2.25rem 1.5rem' },
    backgroundColor: '#001f1ecc',
    border: '1px solid var(--border)',
    borderRadius: '0.5rem',
  },
  loginHeading: { fontSize: 'clamp(3.75rem, 10vw, 6.3125rem)' },
  loginButton: { width: '100%', marginTop: '2.25rem' },
  submission: {
    borderTop: '1px solid var(--border)',
    paddingTop: '1rem',
  },
  submissionLabel: { marginTop: 0 },
  submissionButton: { width: '100%', marginTop: '1rem' },
  submissionSmall: { display: 'block', marginTop: '0.75rem', color: '#ffffff9e' },
  submissionImage: {
    display: 'block',
    width: '100%',
    maxHeight: '18rem',
    objectFit: 'contain',
    borderRadius: '0.5rem',
  },
  fileInput: { height: 'auto', padding: '0.5rem', overflow: 'hidden', borderRadius: '0.5rem' },
  submissionActions: {
    display: 'flex',
    flexDirection: { default: 'row', [mobile]: 'column' },
    gap: '0.75rem',
  },
  ownerSubmissionActions: {
    gridArea: 'actions',
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  ownerList: { display: 'grid', gap: '0.875rem' },
  ownerSubmission: {
    display: 'grid',
    gridTemplateAreas: { default: '"identity score" "actions score" "error error"', [mobile]: '"identity" "score" "actions" "error"' },
    gridTemplateColumns: { default: 'minmax(12rem, 1fr) minmax(14rem, 0.5fr)', [mobile]: '1fr' },
    alignItems: 'end',
    gap: '1rem',
    padding: '1.5rem',
    border: '1px solid var(--border)',
    borderRadius: '0.5rem',
  },
  ownerIdentity: { gridArea: 'identity' },
  ownerScore: { gridArea: 'score', margin: 0 },
  ownerScoreInput: { marginTop: '0.875rem' },
  ownerParagraph: { marginBottom: 0 },
  ownerButton: { margin: 0 },
  ownerError: { gridArea: 'error', margin: 0 },
  error: { color: 'var(--error)' },
})
